#!/bin/bash
#mymenu
. func.sh
. linux.sh
clear
menu

while true
do
	read -p "please input a option:" option

	case $option  in
		1)
			read -p "input a user's name:" name
			if [ ! -e err.log ]
			then
				touch err.log
			fi

			echo "" > err.log
			useradd $name &> err.log

			if [ $? -eq 0 ]
			then
				shellecho  "user ${name} is created successfully!!" 32 40
			else
				err=`cat err.log`
				shellecho "user ${name} is created fail!!" 31 40
				shellecho "error reason is:" 30 47
				shellecho "$err" 31 40
			fi
			;;

		2)
			read -p "input user's name: " name
			read -p "input user ${name} password: " passwd
			echo $passwd | passwd --stdin $name &> err.log

			if [ $? -eq 0 ]
			then
				shellecho  "${name}'s password is set successfully!!" 32 40
			else
				err=`cat err.log`
				shellecho "${name}'s password is set fail!!" 31 40
				shellecho "error reason is:" 30 47
				shellecho "$err" 31 40
			fi
			;;

		3)
			read -p "input user's name: " name
			userdel -r $name &> err.log

			if [ $? -eq 0 ]
			then
				shellecho  "${name}'s delete successfully!!" 32 40
			else
				err=`cat err.log`
				shellecho "${name}'s delete fail!!" 31 40
				shellecho "error reason is:" 30 47
				shellecho "$err" 31 40
			fi
			;;

		4)
			str=`df -Th`
			shellecho "$str" 30 47
			;;

		5)
			str=`free -m`
			shellecho "$str" 30 47
			;;

    6)
      linux_command
      ;;  

		7)
			shellecho 'quit successfully!!' 30 47
			break
			;;

		8)
			clear
			menu
			;;

	esac
done
